#!/usr/bin/python3
""" this script takes a URL and an email send a POST request to the pased URL
- import urllib and sys
"""
import sys
import urllib.request
import urllib.parse
if __name__ == '__main__':
    url = sys.argv[1]
    email_p = sys.argv[2]
    value = {"email" : email_p}
    data = urllib.parse.urlencode(value).encode("ascii")

    request = urllib.request.Request(url, data)
    with urllib.request.urlopen(request) as response:
        print(response.read().decode("utf-8"))
